project:
  type: book
  execute-dir: project
  render:
    - index.qmd
    - "chapters/*.qmd"
    - "appendix/*.qmd"

profile:
  group:
    - [html, pdf, docx]

book:
  chapters:
    - index.qmd
    - chapters/introduction.qmd
    - chapters/methods.qmd
    - chapters/results.qmd
    - chapters/discussion.qmd

bibliography: bibliography/references.bib
csl: bibliography/CSE-N-Y.csl

knitr:
  opts_chunk:
    echo: false
    message: false
    fig-align: center