project:
  type: book
  execute-dir: project
  render:
    - index.qmd
    - "chapters/*.qmd"
    - "appendix/*.qmd"

profile:
  group:
    - [html, pdf]

book:
  chapters:
    - index.qmd
    - chapters/introduction.qmd
    - chapters/methods.qmd
    - chapters/results.qmd
    - chapters/discussion.qmd

bibliography: appendix/references.bib
csl: appendix/council-of-science-editors-author-date.csl

knitr:
  opts_chunk:
    echo: false
    message: false
    results: asis
    fig-align: center
  opts_knit:
    eval.after: "fig.cap"
