project:
  output-dir: ../../_site/thesis/html

book:
  title: "The Systematics of *Physaria* sensu stricto"
  subtitle: "From Wyoming and Surrounding Areas"
  author: Jason Ratcliff
  date: today
  appendices:
    - text: References
      href: appendix/_references.qmd
    - text: Specimens
      href: appendix/_specimens.qmd
    - text: Alignments
      href: appendix/_alignments.qmd
    - text: R Session Info
      href: appendix/_session.qmd

knitr:
  opts_chunk:
    dev: "png"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    fig-height: 12
    fig-width: 8
