image:
  file: .github/gitpod.Dockerfile

tasks:
  - name: Install Development Package
    before: Rscript -e "renv::hydrate(); renv::restore()"
    init: Rscript -e "renv::install('.')"

vscode:
  extensions:
    - REditorSupport.R
