image:
  file: .github/gitpod.Dockerfile

tasks:
  - name: Install Package
    before: Rscript -e "renv::hydrate(); renv::restore()"
    init: Rscript -e "renv::install('.')"

github:
    prebuilds:
        master: true
        branches: false
        pullRequests: true

vscode:
  extensions:
    - REditorSupport.R
