image:
  file: .github/gitpod.Dockerfile

tasks:
  - name: Install Package
    before: Rscript -e "renv::hydrate()"
    init: Rscript -e "renv::install('.')"

vscode:
  extensions:
    - REditorSupport.R
