image:
  file: .github/gitpod.Dockerfile

tasks:
  - name: Install Development Package
    command: Rscript -e "renv::install('.')"

  - name: Open R Console
    command: R

vscode:
  extensions:
    - REditorSupport.R
