
```{r msaAppendix}

# Establish a directory to store alignment appendix msa figures:
alignment_dir <- "Appendix/alignments"
if (!dir.exists(alignment_dir)) {
  dir.create(alignment_dir)
}

# Remove old .aux and .tex files from Alignment-Figures subdirectory.
if (dir.exists(alignment_dir)) {
  alignment_tex_files <-
    list.files(path = alignment_dir, pattern = ".aux|.tex|.fasta",
               full.names = TRUE)
  fs::file_delete(alignment_tex_files)
}

```

\clearpage

```{r msaITS, results = "asis"}

# Write TEXshade files from multiple sequence alignments
ThesisPackage::msa_wrapper(msa_fasta = "rITS-single.fasta", msa_output = "rITS")
tex_files <- list.files(path = fs::path(alignment_dir), full.names = TRUE, 
                        pattern = paste0("rITS_msa_[0-9]+\\.tex"))

# Format TEXshade environments 
purrr::iwalk(.x = tex_files, function(tex_file, index) {
    orientation <- ifelse(index == 1, FALSE, TRUE)
    ThesisPackage::msa_texshade(tex_path = tex_file, landscape = orientation)
  })

cat("\\chapter*{APPENDIX C}",
    "\\addcontentsline{toc}{chapter}{APPENDIX C: ITS SEQUENCE ALIGNMENT}",
    "\\vspace*{12pt}", "\\centering",
    "ITS SEQUENCE ALIGNMENT\n", sep = "\n")

# Walk .Tex files to output LaTeX oriented MSA
purrr::walk(.x = tex_files, function(tex_file) {
  cat(readr::read_lines(file = tex_file), "\\clearpage", sep = "\n")
  })

```

```{r msaRPS, results = "asis"}

# Write TEXshade files from multiple sequence alignments
ThesisPackage::msa_wrapper(msa_fasta = "rps-single.fasta", msa_output = "rps")
tex_files <- list.files(path = fs::path(alignment_dir), full.names = TRUE, 
                        pattern = paste0("rps_msa_[0-9]+\\.tex"))

# Format TEXshade environments 
purrr::iwalk(.x = tex_files, function(tex_file, index) {
    orientation <- ifelse(index == 1, FALSE, TRUE)
    ThesisPackage::msa_texshade(tex_path = tex_file, landscape = orientation)
  })

cat("\\chapter*{APPENDIX D}",
    "\\addcontentsline{toc}{chapter}{APPENDIX D: \\textit{rps} SEQUENCE ALIGNMENT}",
    "\\vspace*{12pt}", "\\centering",
    "\\textit{rps} SEQUENCE ALIGNMENT\n", sep = "\n")

# Walk .Tex files to output LaTeX oriented MSA
purrr::walk(.x = tex_files, function(tex_file) {
  cat(readr::read_lines(file = tex_file), "\\clearpage", sep = "\n")
  })

```

```{r msaYCF1, results = "asis"}

# Write TEXshade files from multiple sequence alignments
ThesisPackage::msa_wrapper(msa_fasta = "ycf1-single.fasta", msa_output = "ycf1")
tex_files <- list.files(path = fs::path(alignment_dir), full.names = TRUE, 
                        pattern = paste0("ycf1_msa_[0-9]+\\.tex"))

# Format TEXshade environments 
purrr::iwalk(.x = tex_files, function(tex_file, index) {
    orientation <- ifelse(index == 1, FALSE, TRUE)
    ThesisPackage::msa_texshade(tex_path = tex_file, landscape = orientation)
  })

cat("\\chapter*{APPENDIX E}",
    "\\addcontentsline{toc}{chapter}{APPENDIX E: \\textit{ycf1} SEQUENCE ALIGNMENT}",
    "\\vspace*{12pt}", "\\centering",
    "\\textit{ycf1} SEQUENCE ALIGNMENT\n", sep = "\n")

# Walk .Tex files to output LaTeX oriented MSA
purrr::walk(.x = tex_files, function(tex_file) {
  cat(readr::read_lines(file = tex_file), "\\clearpage", sep = "\n")
  })

```
