
```{r knitrOptSet, message=FALSE, echo=FALSE, warning=FALSE}

# Set Global knitr chunk and knit options.
knitr::opts_chunk$set(echo=FALSE, results="asis", message=FALSE)
knitr::opts_knit$set(eval.after = 'fig.cap')

# Assign chunk type for knitr chunk sections, kable() calls, and graphics device.
knit_variables <- list()
knit_variables$pandoc <- knitr::opts_knit$get("rmarkdown.pandoc.to")
knit_variables$kable_format <-
  list(html = "html", latex = "latex", docx = "simple")[[knit_variables$pandoc]]
knit_variables$graphics <-
  list(html = "png", latex = "pdf", docx = "png")[[knit_variables$pandoc]]

knitr::opts_chunk$set(dev = knit_variables$graphics)

```

```{r libraries}

# For PDF compilation of Bookdown Doc, LaTeX install required.
library(tinytex)
library(bookdown)
library(knitr)
library(kableExtra)
library(dplyr)

# Load specimen data and Thesis functions.
library(Thesis)

# Initialize list for figure captions.
caption <- list()

# Function to return italized genus name.
physaria <- function(knitr_chunk) {
  paste(
    ifelse(knitr_chunk == "latex",
           "\\textit{Physaria}", "*Physaria*")
  )
}

```
