
```{r setup-intro-priors}
#| include: false
library(thesis)
library(ggplot2)

set.seed(20210311)
```

```{r fig-intro-priors}
#| column: body-outset
#| fig-cap: >
#|   Distribution of *Physaria* herbarium specimen vouchers by prior annotation.
#| fig-align: center
#| fig-height: 12
#| fig-width: 8
SpecimenMap$new(
  records = thesis::herbarium_specimens,
  identifier = "prior_id"
)$filter_limit(
  # Set coordinate extent for specimen plot
  west = -114.5,
  south = 37,
  east = -102,
  north = 49.1
)$filter_taxa(
  paste0(
    "Physaria ",
    c(
      "acutifolia", "brassicoides", "condensata", "dornii",
      "eburniflora", "integrifolia", "vitulifera",
      "'medicinae'", "chambersii", "rollinsii",
      paste("didymocarpa subsp.", c("didymocarpa", "lanata", "lyrata")),
      paste("saximontana subsp.", c("saximontana", "dentata")),
      paste("floribunda subsp.", c("floribunda", "osterhoutii"))
    ),
    "$"
  )
)$map(legend = "Prior Annotations") +
  theme(
    legend.background = element_rect(fill = "grey99"),
    legend.position = "bottom",
    legend.direction = "horizontal",
    plot.margin = margin(0.25, 1, 0.25, 0, "in")
  ) +
  guides(colour = guide_legend(ncol = 3, byrow = TRUE))
```
