#!/bin/bash
#
# AWK script to process .tex files generated by the R package msa 
# (Bodenhofer et al. 2015) which define a TeXshade (Beitz 2000) environment
# for displaying multiple sequence alignments. 
#
# The following arguments can be input:
#   "-F" Awk processed .tex file 
#   "-m" LaTeX minipage argument
#   "-r" Option to rotate printed LaTeX contents 90 degrees
#
# Set default minipage variable 
minipage="FALSE"

# Use builtin function GETOPTS to parse shell variables

while getopts ":F:m:r:" opt ; do
  case "$opt" in
    F)  # Option for .Tex filename output by R msa package
      F="$OPTARG"
      ;;
    m)  # Option for width for latex minipage
      minipage="TRUE"
      m="$OPTARG"
      ;;
    r)  # Optional rotation of alignment TeXshade environment
      r="$OPTARG"
      ;;
    \?) # Warning for non-matching option flags pass as arguments
      echo "Invalid option: -$OPTARG" >&2
      ;;
    :)  # Exit statement for options with a missing argument (i.e. "-F", "-m")
      echo "Option -$OPTARG requires an argument." >&2; exit 1
      ;;
  esac
done

echo "% Latex formatting of "$F # Print comment of TeX file name

# When option "-r" is passed, echo LaTeX formatting to rotate contents.
if [ $r == "ROTATE" ] ; then
  echo "\vfill"               # Fill vertical space
  echo "\centering"           # Center typesetting
  echo "\begin{rotate}{90}"   # Rotate printed contents 90 degrees
fi

# When option "-m" is passed, begin minipage of width "-m" OPTION_ARGUMENT
if [ $minipage == "TRUE" ] ; then
  echo "\begin{minipage}{"$m"}" # Start LaTeX minipage environment
fi

# AWK variable to index the residues per line printed in landscape environments
if [ $r == "LANDSCAPE" ] ; then
  residues="TRUE" 
else 
  residues="FALSE"
fi

# Filter TeX formatted output by R package MSA (Bodenhofer et al. 2015)
awk -v residue="$residues" '

  # Print record that begins the Latex TEXSHADE environment.
  $0 ~ /\\begin{texshade}/ { i = 1; j = 1; begin = NR; print($0); i++ }
  
  # Insert residue 
  { if (i == 2 && residue == "TRUE") { 
    printf "  %s\n", "\\alignment{left}"
    printf "  %s\n", "\\residuesperline*{165}"} 
  }
  
  # Add to i counter and print additional text following TEXSHADE begin.
  { if (i == 2 && j == 1) { i++;
    printf "  %s\n", "\\setsize{numbering}{tiny}"
    printf "  %s\n", "\\setsize{names}{tiny}"
    printf "  %s\n", "\\setsize{residues}{tiny}"
    printf "  %s\n", "\\setsize{consensus}{tiny}" }
  }

  # At record ending TEXSHADE environment, add to j counter and print record.
  $0 ~ /\\end{texshade}/ { j++; print $0 }
  
  # Print records between "\begin{texshade}" and "\end{texshade}".
  { 
    if (i == 3 && j == 1 && NR > begin) { printf "  %s\n", $0 }
  }' $F # Shell variable of path to .tex file generated by msaPrettyPrint() in R

if [ $minipage == "TRUE" ] ; then
  echo "\end{minipage}" # End minipage environment
fi

if [ $r == "ROTATE" ] ; then 
  echo "\end{rotate}" # End rotate environment
fi

