spp_color <- c(
  "Physaria" = "seashell",
  "Physaria flowering" = "seashell",
  "Physaria acutifolia" = "yellow4",
  "Physaria brassicoides" = "olivedrab2",
  "Physaria vitulifera" = "darkturquoise",
  "Physaria medicinae" = "darkorchid",
  "Physaria acutifolia - vitulifera-like" = "plum",
  "Physaria vitulifera - Carbon" = "steelblue",
  "Physaria floribunda" = "red",
  "Physaria floribunda ssp. floribunda" = "red",
  "Physaria floribunda ssp. osterhoutii" = "azure4",
  "Physaria rollinsii" = "darkorchid1",
  "Physaria bellii" = "blue",
  "Physaria alpina" = "firebrick",
  "Physaria geyeri" = "plum1",
  "Physaria chambersii" = "springgreen",
  "Physaria didymocarpa ssp. didymocarpa" = "skyblue",
  "Physaria didymocarpa ssp. lanata" = "goldenrod",
  "Physaria didymocarpa ssp. lyrata"= "black",
  "Physaria saximontana ssp. dentata" = "maroon",
  "Physaria saximontana ssp. saximontana" = "indianred",
  "Physaria eburniflora" = "cyan",
  "Physaria integrifolia" =  "seagreen",
  "Physaria dornii" = "darkorange",
  "Physaria condensata"= "mediumblue",
  "Physaria obcordata" = "black",
  "Physaria fendleri" = "black",
  "Physaria argyraea" = "black"
  )

spp_shape <- c(
  "Physaria" = 16,
  "Physaria flowering" = 16,
  "Physaria acutifolia" = 3,
  "Physaria brassicoides" = 16,
  "Physaria vitulifera"= 18,
  "Physaria medicinae" = 18,
  "Physaria acutifolia - vitulifera-like" = 18,
  "Physaria vitulifera - Carbon" = 18,
  "Physaria floribunda" = 0,
  "Physaria floribunda ssp. floribunda" = 0,
  "Physaria floribunda ssp. osterhoutii" = 5,
  "Physaria rollinsii" = 17,
  "Physaria bellii" = 17,
  "Physaria alpina" = 17,
  "Physaria geyeri" = 17,
  "Physaria chambersii" = 17,
  "Physaria didymocarpa ssp. didymocarpa" = 15,
  "Physaria didymocarpa ssp. lanata" = 15,
  "Physaria didymocarpa ssp. lyrata" = 15,
  "Physaria saximontana ssp. dentata" = 15,
  "Physaria saximontana ssp. saximontana" = 15,
  "Physaria eburniflora" = 15,
  "Physaria integrifolia" = 16,
  "Physaria dornii" = 16,
  "Physaria condensata"= 16,
  "Physaria obcordata" = 16,
  "Physaria fendleri" = 15,
  "Physaria argyraea" = 18
  )

# Save objects as internal R data
usethis::use_data(spp_color, spp_shape, overwrite = TRUE)

